CREATE TABLE `fixed_zones` (

  
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  
  `name` VARCHAR(100) DEFAULT NULL,  
  
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` DATETIME DEFAULT NULL,


  PRIMARY KEY (`id`),

  UNIQUE KEY `id` (`id`)

) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;