/**
 * Policy Mappings
 * (sails.config.policies)
 *
 * Policies are simple functions which run **before** your actions.
 *
 * For more information on configuring policies, check out:
 * https://sailsjs.com/docs/concepts/policies
 */

module.exports.policies = {
  /***************************************************************************
   *                                                                          *
   * Default policy for all controllers and actions, unless overridden.       *
   * (`true` allows public access)                                            *
   *                                                                          *
   ***************************************************************************/

  // '*': true,
  AdminController: {
    // '*': 'isAdminLoggedIn',
    // Allow anyone to access the login action, even if they're not logged in.
    login: true,
    users: true,
  },
  UserController: {
    //  '*': 'isAdminLoggedIn',
    // Allow anyone to access the login action, even if they're not logged in.
    login: true,
    users: true,
  },
  "user/change-password": ["isLoggedIn"],
  "user/change-language": ["isLoggedIn"],
  "user/create-rfp": ["isLoggedIn"],
  "user/cancel-rfp": ["isLoggedIn"],
  "user/respond-proposal": ["isLoggedIn"],
  "user/create-review-rating": ["isLoggedIn"],
  //"user/get-nearby-stores": ["isLoggedIn"],
  "user/store-quick-info": ["isLoggedIn"],
  //"user/store-detail-info": ["isLoggedIn"],
  "user/store-detail-info": ["isTokenProvided"],
  //"user/store-policy": ["isLoggedIn"],
  "user/get-assigned-stores": ["isLoggedIn"],
  //"user/store-reviews-ratings": ["isLoggedIn"],
  // "user/store-categories": ["isLoggedIn"],
  //"user/category-detail": ["isLoggedIn"],
  //"user/search-products": ["isLoggedIn"],
  //"user/store-products": ["isLoggedIn"],
  "user/edit-profile": ["isLoggedIn"],
  "user/add-location": ["isLoggedIn"],
  "user/edit-location": ["isLoggedIn"],
  "user/delete-location": ["isLoggedIn"],
  "user/locations": ["isLoggedIn"],
  "user/order-listing": ["isLoggedIn"],
  "user/order-detail": ["isLoggedIn"],
  "user/order-status": ["isLoggedIn"],
  "user/my-orders-listing": ["isLoggedIn"],
  "user/my-order-detail": ["isLoggedIn"],
  "user/my-order-proposals": ["isLoggedIn"],
  "user/my-order-proposal-detail": ["isLoggedIn"],
  "user/my-order-history": ["isLoggedIn"],
  "user/my-order-history-detail": ["isLoggedIn"],
  "user/revise-proposal": ["isLoggedIn"],
  "user/submit-contact-us": ["isLoggedIn"],
  "user/faq-listing": ["isTokenProvided"],
  "user/update-avatar": ["isLoggedIn"],
  "user/close-rfp": ["isLoggedIn"],
  "user/make-payment": ["isLoggedIn"],
  "user/device-token": ["isLoggedIn"],
  "user/queue-status": ["isLoggedIn"],
  "user/reviews-ratings": ["isLoggedIn"],
  "user/is-order-rated": ["isLoggedIn"],
  // 'user/waspha-terms-n-conditions':['isLoggedIn'],
  // 'user/waspha-privacy-policy':['isLoggedIn'],
  "user/notification-listing": ["isLoggedIn"],
  "user/mark-as-read": ["isLoggedIn"],
  "user/get-wallet": ["isLoggedIn"],
  "user/logout": ["isLoggedIn"],
  "user/promo-codes": ["isLoggedIn"],
  "user/apply-promo-code": ["isLoggedIn"],
  "user/active-orders": ["isLoggedIn"],
  "user/save-is-device-active": ["isLoggedIn"],
  "user/get-ad": ["isLoggedIn"],
  "user/change-contact-or-email": ["isLoggedIn"],
  "user/verify-contact-or-email": ["isLoggedIn"],

  "vendor/change-password": ["isVendorLoggedIn"],
  "vendor/device-token": ["isVendorLoggedIn"],
  "vendor/add-store": ["isVendorLoggedIn"],
  "vendor/edit-store": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/edit-profile": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/update-store-attributes": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/add-business-category": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/edit-business-category": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/delete-business-category": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
  ],
  "vendor/business-category-listing": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
  ],
  "vendor/add-product": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/edit-product": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/delete-product": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/create-proposal": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/update-proposal": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/confirm-bill": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/change-proposal-delivery-mode": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/proposal-listing": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/proposal-detail": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/proposal-invoice": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/rfp-listing": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/rfp-detail": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/store-reviews-ratings": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/create-review-rating": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/store-profile": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/store-dashboard": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/store-earning": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/add-driver": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/edit-driver": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/delete-driver": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/store-drivers": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/assign-driver": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/faq-listing": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/respond-rfp": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/submit-contact-us": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/change-language": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/search-products": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/trending-products": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/notification-listing": ["isVendorLoggedIn"],
  "vendor/mark-as-read": ["isVendorLoggedIn"],
  "vendor/mark-as-viewed": ["isVendorLoggedIn"],
  "vendor/get-count-marked-as-viewed": ["isVendorLoggedIn"],
  "vendor/store-products": ["isVendorLoggedIn", "isBusinessRegistered"],
  "vendor/change-proposal-status": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/is-order-rated": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/promo-codes": [
    "isVendorLoggedIn",
    "isBusinessRegistered",
    "isVendorApproved",
  ],
  "vendor/logout": ["isVendorLoggedIn"],
  "vendor/active-orders": ["isVendorLoggedIn"],
  "vendor/create-traditional-order": ["isVendorLoggedIn"],
  "vendor/traditional-order-listing": ["isVendorLoggedIn"],
  "vendor/traditional-order-detail": ["isVendorLoggedIn"],
  "vendor/assign-waspha-driver": ["isVendorLoggedIn"],
  "vendor/cancel-order": ["isVendorLoggedIn"],
  "vendor/get-waspha-driver-vehicles": ["isVendorLoggedIn"],
  "vendor/is-order-assigned": ["isVendorLoggedIn"],
  "vendor/save-is-device-active": ["isVendorLoggedIn"],
  "vendor/get-ad": ["isVendorLoggedIn"],
  "vendor/change-contact-or-email": ["isVendorLoggedIn"],
  "vendor/verify-contact-or-email": ["isVendorLoggedIn"],

  // 'vendor/waspha-terms-n-conditions':['isVendorLoggedIn'],
  // 'vendor/waspha-privacy-policy':['isVendorLoggedIn'],

  "super-admin/add-category": ["isAdminLoggedIn"],
  "super-admin/edit-category": ["isAdminLoggedIn"],
  "super-admin/delete-category": ["isAdminLoggedIn"],
  "super-admin/delete-categories": ["isAdminLoggedIn"],
  "super-admin/edit-category-timeouts": ["isAdminLoggedIn"],
  "super-admin/get-category-timeout": ["isAdminLoggedIn"],
  "super-admin/change-vendor-status": ["isAdminLoggedIn"],
  "super-admin/add-faq": ["isAdminLoggedIn"],
  "super-admin/get-users": ["isAdminLoggedIn"],
  "super-admin/add-user": ["isAdminLoggedIn"],
  "super-admin/get-addresses": ["isAdminLoggedIn"],
  "super-admin/get-categories": ["isAdminLoggedIn"],
  "super-admin/get-user": ["isAdminLoggedIn"],
  //'super-admin/update-user': ['isAdminLoggedIn'],
  "super-admin/create-user": ["isAdminLoggedIn"],
  "super-admin/delete-user": ["isAdminLoggedIn"],
  "super-admin/delete-users": ["isAdminLoggedIn"],
  "super-admin/create-role": ["isAdminLoggedIn", "isSuperAdmin"],
  "super-admin/get-roles": ["isAdminLoggedIn"],
  "super-admin/update-role": ["isAdminLoggedIn", "isSuperAdmin"],
  "super-admin/delete-role": ["isAdminLoggedIn", "isSuperAdmin"],
  "super-admin/get-role": ["isAdminLoggedIn"],
  "vt-admin/create-permission": ["isAdminLoggedIn", "isVTAdmin"],
  "vt-admin/update-permission": ["isAdminLoggedIn", "isVTAdmin"],
  "vt-admin/delete-permission": ["isAdminLoggedIn", "isVTAdmin"],
  "super-admin/get-permissions": ["isAdminLoggedIn"],
  "super-admin/get-permission": ["isAdminLoggedIn"],
  "super-admin/assign-permissions": ["isAdminLoggedIn", "isSuperAdmin"],
  "super-admin/send-message": ["isAdminLoggedIn", "isSuperAdmin"],
  "super-admin/get-vendors": ["isAdminLoggedIn"],
  "super-admin/get-vendor": ["isAdminLoggedIn"],
  "super-admin/edit-vendor": ["isAdminLoggedIn"],
  "super-admin/delete-vendor": ["isAdminLoggedIn"],
  "super-admin/delete-proposal": ["isAdminLoggedIn"],
  "super-admin/delete-proposals": ["isAdminLoggedIn"],
  "super-admin/delete-rfp": ["isAdminLoggedIn"],
  "super-admin/delete-rfps": ["isAdminLoggedIn"],
  "super-admin/delete-driver": ["isAdminLoggedIn"],
  "super-admin/delete-drivers": ["isAdminLoggedIn"],
  "super-admin/get-driver": ["isAdminLoggedIn"],
  "super-admin/get-vehicles": ["isAdminLoggedIn"],
  "super-admin/add-driver": ["isAdminLoggedIn"],
  "super-admin/edit-driver": ["isAdminLoggedIn"],
  "super-admin/get-proposals": ["isAdminLoggedIn"],
  "super-admin/get-proposal": ["isAdminLoggedIn"],

  "super-admin/get-reviews": ["isAdminLoggedIn"],
  "super-admin/get-translations": ["isAdminLoggedIn"],
  "super-admin/get-translation": ["isAdminLoggedIn"],
  "super-admin/add-translation": ["isAdminLoggedIn"],
  "super-admin/edit-translation": ["isAdminLoggedIn"],
  "super-admin/get-notification-templates": ["isAdminLoggedIn"],
  "super-admin/get-notification-template": ["isAdminLoggedIn"],
  "super-admin/edit-notification-template": ["isAdminLoggedIn"],
  "super-admin/get-promo-codes": ["isAdminLoggedIn"],
  "super-admin/add-promo-code": ["isAdminLoggedIn"],
  "super-admin/get-promo-code": ["isAdminLoggedIn"],
  "super-admin/delete-promo-code": ["isAdminLoggedIn"],
  "super-admin/delete-promo-codes": ["isAdminLoggedIn"],
  "super-admin/edit-promo-code": ["isAdminLoggedIn"],
  "super-admin/get-reports": ["isAdminLoggedIn"],
  "super-admin/get-report": ["isAdminLoggedIn"],
  "super-admin/get-driver-reports": ["isAdminLoggedIn"],
  "super-admin/get-driver-report": ["isAdminLoggedIn"],
  "super-admin/get-screen-contents": ["isAdminLoggedIn"],
  "super-admin/get-screen-content": ["isAdminLoggedIn"],
  "super-admin/change-online-status": ["isAdminLoggedIn"],
  "super-admin/edit-store-attributes": ["isAdminLoggedIn"],
  "super-admin/get-settings": ["isAdminLoggedIn"],
  "super-admin/get-setting": ["isAdminLoggedIn"],
  "super-admin/edit-setting": ["isAdminLoggedIn"],
  "super-admin/get-commissions": ["isAdminLoggedIn"],
  "super-admin/get-commission": ["isAdminLoggedIn"],
  "super-admin/add-commission": ["isAdminLoggedIn"],
  "super-admin/edit-commission": ["isAdminLoggedIn"],
  "super-admin/get-driver-commissions": ["isAdminLoggedIn"],
  "super-admin/get-driver-commission": ["isAdminLoggedIn"],
  "super-admin/add-driver-commission": ["isAdminLoggedIn"],
  "super-admin/edit-driver-commission": ["isAdminLoggedIn"],
  "super-admin/get-cancellation-reasons": ["isAdminLoggedIn"],
  "super-admin/get-cancellation-reason": ["isAdminLoggedIn"],
  "super-admin/get-cancellation-reason-item": ["isAdminLoggedIn"],
  "super-admin/edit-cancellation-reason-item": ["isAdminLoggedIn"],
  "super-admin/make-payment-to-vendor": ["isAdminLoggedIn"],
  "super-admin/receive-payment-from-vendor": ["isAdminLoggedIn"],
  "super-admin/change-driver-status": ["isAdminLoggedIn"],
  "super-admin/add-zone-option": ["isAdminLoggedIn"],
  "super-admin/get-zones": ["isAdminLoggedIn"],
  "super-admin/get-zone": ["isAdminLoggedIn"],
  "super-admin/add-zone": ["isAdminLoggedIn"],
  "super-admin/edit-zone": ["isAdminLoggedIn"],
  "super-admin/update-vendor-subscription-waspha-express": ["isAdminLoggedIn"],
  "super-admin/update-vendor-services": ["isAdminLoggedIn"],
  "super-admin/get-admins": ["isAdminLoggedIn"],
  "super-admin/get-admin": ["isAdminLoggedIn"],
  "super-admin/add-admin": ["isAdminLoggedIn"],

  "super-admin/get-delivery-vehicle-charges": ["isAdminLoggedIn"],
  "super-admin/get-delivery-vehicle-charge": ["isAdminLoggedIn"],
  "super-admin/add-delivery-vehicle-charge": ["isAdminLoggedIn"],
  "super-admin/edit-delivery-vehicle-charge": ["isAdminLoggedIn"],
  "super-admin/get-delivery-vehicles": ["isAdminLoggedIn"],
  "super-admin/get-delivery-vehicle": ["isAdminLoggedIn"],
  "super-admin/add-delivery-vehicle": ["isAdminLoggedIn"],
  "super-admin/edit-delivery-vehicle": ["isAdminLoggedIn"],
  "super-admin/get-ads": ["isAdminLoggedIn"],
  "super-admin/get-ad": ["isAdminLoggedIn"],
  "super-admin/add-ad": ["isAdminLoggedIn"],
  "super-admin/edit-ad": ["isAdminLoggedIn"],
  "super-admin/get-store-products": ["isAdminLoggedIn"],
  "super-admin/get-store-product": ["isAdminLoggedIn"],
  "super-admin/add-store-product": ["isAdminLoggedIn"],
  "super-admin/edit-store-product": ["isAdminLoggedIn"],
  "super-admin/delete-store-product": ["isAdminLoggedIn"],
  "super-admin/get-store-categories": ["isAdminLoggedIn"],
  "super-admin/get-store-category": ["isAdminLoggedIn"],
  "super-admin/add-store-category": ["isAdminLoggedIn"],
  "super-admin/edit-store-category": ["isAdminLoggedIn"],
  "super-admin/delete-store-category": ["isAdminLoggedIn"],
  "super-admin/get-waspha-countries": ["isAdminLoggedIn"],
  "super-admin/add-waspha-country": ["isAdminLoggedIn"],
  "super-admin/delete-waspha-country": ["isAdminLoggedIn"],
  "super-admin/delete-waspha-countries": ["isAdminLoggedIn"],
  "super-admin/get-rfps": ["isAdminLoggedIn"],
  "super-admin/get-rfp": ["isAdminLoggedIn"],
  "super-admin/get-wallets": ["isAdminLoggedIn"],
  "super-admin/get-wallet": ["isAdminLoggedIn"],
  "super-admin/get-countries": ["isAdminLoggedIn"],

  ///Driver
  "driver/logout": ["isDriverLoggedIn"],
  "driver/change-password": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/device-token": ["isDriverLoggedIn"],
  "driver/change-language": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/submit-contact-us": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/faq-listing": ["isDriverLoggedIn"],
  "driver/change-online-status": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/order-request": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/respond-order-request": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/cancel-order-request": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/change-ride-status": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/earnings": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/trips-earnings": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/trips-n-orders": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/profile": ["isDriverLoggedIn"],
  "driver/edit-profile": ["isDriverLoggedIn"],
  "driver/reviews-ratings": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/create-review-rating": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/add-to-wallet": ["isDriverLoggedIn", "isDriverApproved"],
  "driver/notification-listing": ["isDriverLoggedIn"],
  "driver/mark-as-read": ["isDriverLoggedIn"],
  "driver/is-order-rated": ["isDriverLoggedIn"],
  "driver/update-avatar": ["isDriverLoggedIn"],
  "driver/active-orders": ["isDriverLoggedIn"],
  "driver/save-zone": ["isDriverLoggedIn"],
  "driver/get-ad": ["isDriverLoggedIn"],
  "driver/change-contact-or-email": ["isDriverLoggedIn"],
  "driver/verify-contact-or-email": ["isDriverLoggedIn"],
};
