module.exports.strings = {
  en: {
    EMAIL_ALREADY_EXIST:
      "A user with the same email is already registered, please use a different email address",
    CONTACT_ALREADY_EXIST:
      "A user with the same Phone number is already registered, please use a different phone number",
    EMAIL_ALREADY_EXIST_DRIVER:
      "A driver with the same email is already registered, please use a different email address",
    CONTACT_ALREADY_EXIST_DRIVER:
      "A driver with the same Phone number is already registered, please use a different phone number",
    SIGNUP_REQUEST_SUBMITTED: "Signed up request submitted successfully",
    INVALID_EMAIL_OR_OTP: "Invalid email or OTP",
    INVALID_CONTACT_OR_OTP: "Invalid contact or OTP",
    INVALID_EMAIL: "Invalid email",
    INVALID_PHONE: "Invalid phone number",
    SIGNED_UP: "Signed up successfully",
    UNABLE_TO_SIGNUP: "Unable to signup",
    CODE_SENT_TO_EMAIL_VENDOR:
      "Code will be sent to your email address if you are a registered vendor",
    CODE_SENT_TO_PHONE_VENDOR:
      "Code will be sent to your phone number if you are a registered vendor",
    CODE_SENT_TO_EMAIL_USER:
      "Code will be sent to your email address if you are a registered user",
    CODE_SENT_TO_PHONE_USER:
      "Code will be sent to your phone number if you are a registered user",
    INVALID_VENDOR_ID: "Invalid vendor id",
    INVALID_VENDOR_ID_OR_OTP: "Invalid vendor id or OTP",
    INVALID_OTP: "Invalid OTP",
    INVALID_VENDOR_ID_OR_PASSWORD:
      "Either your vendor id or password is incorrect",
    INVALID_USER_ID_OR_PASSWORD: "Either your user id or password is incorrect",
    INVALID_USER_ID: "Invalid user id",
    INVALID_USER_ID_OR_OTP: "Invalid user id or OTP",
    INVALID_RFP_ID: "Invalid RFP id",
    RFP_CANCELLED: "RFP cancelled successfully",
    STORES_FOUND: "{total} store(s) found successfully",
    STORES_NOT_FOUND: "Stores not found",
    UNABLE_TO_CANCEL_RFP: "Unable to cancel RFP",
    LOGGED_IN: "Logged in successfully",
    UNABLE_TO_LOGIN: "Unable to login",
    LOGGED_OUT: "Logged out successfully",
    UNABLE_TO_LOGOUT: "Unable to logout",
    UNABLE_TO_LOGIN_INVALID_TOKEN: "Unable to login, invalid token",
    OTP_SENT: "opt sent successfully",
    YOU_CAN_RESET_PASSWORD_NOW: "You can reset password now",
    YOU_ENTERED_OLD_PASSWORD:
      "You have entered old password, please provide a new password ",
    PASSWORD_RESET: "Password reset successfully",
    UNABLE_TO_RESET_PASSWORD: "Unable to reset password",
    EMAIL_OR_PASSWORD_INCORRECT: "Email or password incorrect",
    TOKEN_RESUMED: "Token resumed successfully",
    UNABLE_TO_RESUME_TOKEN: "Unable to resume token",
    LANGUAGE_CHANGED: "Language changed successfully",
    UNABLE_TO_CHANGE_LANGUAGE:
      "Unable to change language. Please try again later",
    PROPOSAL_CREATED: "Proposal created successfully",
    PROPOSAL_UPDATED: "Proposal updated successfully",
    UNABLE_TO_CREATE_PROPOSAL: "Unable to create proposal",
    UNABLE_TO_UPDATE_PROPOSAL: "Unable to update proposal",
    PROPOSAL_ALREADY_EXITS: "Propsal already exists",
    REVIEWS_FOUND: "{total} review(s) found successfully",
    REVIEWS_NOT_FOUND: "Reviews & ratings not found",
    PRODUCTS_FOUND: "{total} product(s) found successfully",
    PRODUCTS_NOT_FOUND: "Products not found",
    CATEGORIES_FOUND: "{total} category(s) found successfully",
    CATEGORIES_NOT_FOUND: "Category(s) not found",
    PROFILE_UPDATED: "Profile updated successfully",
    UPDATED: "Updated successfully",
    UNABLE_TO_UPDATE: "Unable to update",
    NOTHING_TO_UPDATE: "Nothing to update",
    CREATED: "Created successfully",
    UNABLE_TO_CREATE: "Unable to create",
    INVALID_ID: "Invalid id",
    PROPOSALS_FOUND: "{total} proposal(s) found successfully",
    PROPOSAL_FOUND: "Proposal found successfully",
    PROPOSALS_NOT_FOUND: "Proposals not found",
    PROPOSAL_NOT_FOUND: "Proposal not found",
    ANOTHER_ORDER_ASSIGNED_TO_DRIVER_ALREADY:
      "Another order is assigned to this driver already",
    ASSIGNED_TO_DRIVER: "Assigned to driver successfully",
    INVALID_ORDER_ID: "Invalid order id",
    UNABLE_TO_ASSIGN_DRIVER: "Unable to assign driver",
    LOCATIONS_FOUND: "{total} locations found successfully",
    LOCATIONS_NOT_FOUND: "Locations not found",
    UNABLE_TO_FIND_LOCATIONS: "Unable to find locations",
    BUSINESS_ALREADY_REGISTERED: "Business already registered",
    BUSINESS_EXISTS_WITH_PHONE_NO: "Business with phone number already exists",
    BUSINESS_REGISTRATION_REQUIRED: "Business registration is required",
    BUSINESS_REGISTERED:
      "Business registered successfully, requires admin approval",
    BUSINESS_PROFILE_UPDATED:
      "Business profile updated successfully, requires admin approval",
    TOTAL_USERS_FOUND: "{total} users found successfully",
    INVALID_PROPOSAL_ID: "Invalid Proposal id",
    PROPOSAL_RESPONDED: "Proposal {status} successfully",
    ROLE_ALREADY_EXISTS: "Role with this name already exists",
    TOTAL_ROLES_FOUND: "{total} role(s) found successfully",
    TOTAL_RECORDS_FOUND: "{total} {records} found successfully",
    ROLE_FOUND: "Role found successfully",
    ROLES_NOT_FOUND: "Roles not found",
    INVALID_ROLE_ID: "Invalid role id",
    EMAIL_PASSWORD_REQUIRED_FOR_ONLINE_DRIVER:
      "Email & password is required for online driver",
    DRIVER_ADDED: "Driver added successfully",
    UNABLE_TO_ADD_DRIVER: "Unable to add driver",
    DELETED: "Deleted successfully",
    UNABLE_TO_DELETE: "Uable to delete",
    ROLE_CANT_BE_DELETED: "This role can not be deleted",
    PERMISSION_ALREADY_EXISTS: "Permission with this name already exists",
    PERMISSIONS_FOUND: "Permissions found successfully",
    PERMISSIONS_NOT_FOUND: "Permissions not found",
    ORDER_FOUND: "Order found successfully",
    ORDER_NOT_FOUND: "Order not found",
    PROCESSED_SUCCESSFULLY: "Processed successfully",
    UNABLE_TO_PROCESS: "Unable to process",
    PROPOSAL_REVISED: "Proposal revised successfully",
    SOME_INVALID_ITEMS: "Payload contains some invalid items",
    PERMISSIONS_ASSIGNED: "Permissions assigned successfully",
    UNABLE_TO_ASSIGN_PERMISSIONS: "Unable to assign permissions",
    INVALID_DRIVER_ID: "Invalid driver id",
    DRIVER_IS_OFFLINE: "Driver is offline",
    DRIVER_UPDATED: "Driver updated successfully",
    DRIVER_DELETED: "Driver deleted successfully",
    FORM_SUBMITTED: "Form submitted successfully",
    UNABLE_TO_SUBMIT_FORM: "Unable to submit form",
    STATUS_CHANGED: "Status changed successfully",
    UNABLE_TO_CHANGE_STATUS: "Unable to change status",
    ORDER_REQUEST_FOUND: "Order request found successfully",
    UNABLE_TO_GET_ORDER_REQUEST: "Unable to get order request",
    FOUND: "Found successfully",
    NOT_FOUND: "Not found",
    DRIVERS_FOUND: "{total} driver(s) found successfully",
    DRIVERS_NOT_FOUND: "Drivers not found",
    INVALID_ORDER_REQUEST_ID: "Invalid order request id",
    PROCESSED_SUCCESSFULLY: "Processed successfully",
    UNABLE_TO_PROCESS: "Unable to process",
    ACCEPTED_SUCCESSFULLY: "Accepted successfully",
    REJECTED_SUCCESSFULLY: "Rejected successfully",
    CANCELLED_SUCCESSFULLY: "Cancelled successfully",
    VERIFICATION_CODE_REQUIRED: "Verification code is required",
    INVALID_VERIFICATION_CODE: "Invalid verification code",
    VEHICLE_CHANGED: "Vehicle changed successfully",
    UNABLE_TO_CHANGE_VEHICLE: "Unable to change vehicle",
    INVALID_VEHICLE_ID: "Invalid vehicle id",
    INVALID_CATEGORY_ID: "Invalid category id",
    INVALID_PRODUCT_ID: "Invalid product id",
    DRIVER_HAS_DIFFERENT_VEHICLE: "Driver has different vehicle",
    FOUND: "Found successfully",
    NOT_FOUND: "Not found",
    YOU_DONT_HAVE_ENOUGH_CREDIT: "You do not have enough credit for payment",
    PAID: "Paid successfully",
    ADDED_TO_WALLET: "Added to wallet successfully",
    DELIVERY_MODE_AND_DELIVERY_VEHICLE_REQUIRED:
      "Delivery mode & Delivery vehicle are required",
    RFP_HAS_BEEN_EXPIRED: "RFP has been expired",
    RFP_HAS_BEEN_CANCELLED: "RFP has been cancelled",
    FORGET_PASSWORD_EMAIL_MSG:
      "<p>Waspha Forget Password OTP is <b>: {OTP} </b></p>",
    FORGET_PASSWORD_PHONE_MSG: "Waspha Forget Password OTP is: {OTP}",
    RESEND_OTP_EMAIL_MSG: "<p>Waspha Verification OTP is <b>: {OTP} </b></p>",
    RESEND_OTP_PHONE_MSG: "Waspha Verification OTP is: {OTP}",
    CATEGORY_WITH_SLUG_ALREADY_EXIST: "Category with this slug already exists",
    CATEGORY_WITH_NAME_ALREADY_EXIST: "Category with this name already exists",
    INVALID_PARENT_ID: "Invalid parent id",
    UNABLE_TO_REGISTER: "Unable to register",
    INCORRECT_OLD_PASSWORD: "Incorrect old password",
    CHANGED: "Changed successfully",
    UNABLE_TO_CHANGE: "Unable to change",
    CONFIRMED: "Confirmed successfully",
    UNABLE_TO_CONFIRM: "Unable to confirm",
    SUBMITTED: "Submitted successfully",
    UNABLE_TO_SUBMIT: "Unable to submit",
    UNABLE_TO_FIND: "Unable to find",
    INVALID_PROMO_CODE: "Invalid promo code",
    APPLIED: "Applied successfully",
    YOU_ARE_NOT_ALLOWED_TO_USE_THIS_PROMO:
      "You are not allowed to use this promo code",
    PROMO_IS_NOT_APPLICABLE_TO_SELECTED_PAYMENT_METHOD:
      "Promo code is not applicable to selected payment method",
    PROMO_IS_NOT_APPLICABLE_TO_SELECTED_SERVICE_MODE:
      "Promo code is not applicable to selected service mode",
    PROMO_IS_NOT_APPLICABLE_TO_SELECTED_CATEGORY:
      "Promo code is not applicable to selected category",
    PROMO_LIMIT_REACHED: "Promo code limit has been reached",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_SUBTOTAL:
      "Promo code minimum order amount not reached on subtotal",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_TOTAL:
      "Promo code minimum order amount not reached on total",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_DELIVERY_FEE:
      "Promo code minimum order amount not reached on delivery fee",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_WASPHA_FEE:
      "Promo code minimum order amount not reached on Waspha fee",
    YOU_CANT_REVISE_WITH_ZERO_QUANTITY: "You can not revise with zero quantity",
    PASSWORD_CHANGED: "Password changed successfully",
    INVALID_STORE_ID: "Invalid store id",
    YOU_HAVE_AN_ACTIVE_ORDER_ALREADY: "You have an active order already",
    INVALID_SUBCATEGORY: "Invalid subcategory id",
    RFP_CREATED: "RFP created successfully",
    CODE_SENT_IF_YOU_ARE_REGISTERED_USER:
      "Code sent if you are a registered user",
    UNABLE_TO_CHANGE_DELIVERY_MODE_AVAILABILITY:
      "Unable to change delivery mode availability",
    ADDED: "Added successfully",
    ADMIN_APPROVAL_REQUIRED: "Admin approval is required",
    PLEASE_SPECIFY_FIXED_ZONE_OR_FREE_ZONE:
      "Please specify fixed zone or free zone",
    INVALID_FIXED_ZONE_ID: "Invalid fixed zone id",
    NO_NEED_TO_CHANGE: "No need to change",
    INVALID_REFERRAL_CODE: "Invalid referral code",
    VERIFY_EMAIL_MSG: "<p>Waspha Verify Email OTP is <b>: {OTP} </b></p>",
    VERIFY_CONTACT_MSG: "<p>Waspha Verify Phone OTP is <b>: {OTP} </b></p>",
    EMAIL_VERIFIED: "Email verified successfully",
    CONTACT_VERIFIED: "Phone verified successfully",
    EMAIL_IS_SAME: "Email is same,no need to change",
    CONTACT_IS_SAME: "Contact is same,no need to change",
    FORGET_PASSWORD: "Forget Password",
    RESEND_OTP: "Resend OTP",
    FROM: "from",
    TO: "to",
    FULLTIME: "fulltime",
    DAY: {
      Sunday: "Sunday",
      Monday: "Monday",
      Tuesday: "Tuesday",
      Wednesday: "Wednesday",
      Thursday: "Thursday",
      Friday: "Friday",
      Saturday: "Saturday",
    },
    MONTH: {
      January: "January",
      February: "February",
      March: "March",
      April: "April",
      May: "May",
      June: "June",
      July: "July",
      August: "August",
      September: "September",
      October: "October",
      November: "November",
      December: "December",
    },
  },
  ar: {
    EMAIL_ALREADY_EXIST:
      "تم تسجيل مستخدم بنفس البريد الإلكتروني بالفعل ، يرجى استخدام عنوان بريد إلكتروني مختلف",
    CONTACT_ALREADY_EXIST:
      "تم تسجيل مستخدم له نفس رقم الهاتف بالفعل ، يرجى استخدام رقم هاتف مختلف",
    EMAIL_ALREADY_EXIST_DRIVER:
      "تم تسجيل سائق بنفس البريد الإلكتروني بالفعل ، يرجى استخدام عنوان بريد إلكتروني مختلف",
    CONTACT_ALREADY_EXIST_DRIVER:
      "سائق بنفس رقم الهاتف مسجل بالفعل ، يرجى استخدام رقم هاتف مختلف",
    SIGNUP_REQUEST_SUBMITTED: "تم إرسال طلب التسجيل بنجاح",
    INVALID_EMAIL_OR_OTP: "بريد إلكتروني أو OTP غير صالح",
    INVALID_CONTACT_OR_OTP: "جهة اتصال أو OTP غير صالح",
    INVALID_EMAIL: "بريد إلكتروني خاطئ",
    INVALID_PHONE: "رقم الهاتف غير صحيح",
    SIGNED_UP: "تم التسجيل بنجاح",
    UNABLE_TO_SIGNUP: "غير قادر على التسجيل",
    CODE_SENT_TO_EMAIL_VENDOR:
      "سيتم إرسال الرمز إلى عنوان بريدك الإلكتروني إذا كنت بائعًا مسجلاً",
    CODE_SENT_TO_PHONE_VENDOR:
      "سيتم إرسال الرمز إلى رقم هاتفك إذا كنت بائعًا مسجلاً",
    CODE_SENT_TO_EMAIL_USER:
      "سيتم إرسال الرمز إلى عنوان بريدك الإلكتروني إذا كنت مستخدمًا مسجلاً",
    CODE_SENT_TO_PHONE_USER:
      "سيتم إرسال الرمز إلى رقم هاتفك إذا كنت مستخدمًا مسجلاً",
    INVALID_VENDOR_ID: "معرف البائع غير صالح",
    INVALID_VENDOR_ID_OR_OTP: "معرف البائع أو OTP غير صالح",
    INVALID_OTP: "OTP غير صالح",
    INVALID_VENDOR_ID_OR_PASSWORD:
      "إما أن معرف البائع أو كلمة المرور غير صحيحة",
    INVALID_USER_ID_OR_PASSWORD:
      "إما أن معرف المستخدم أو كلمة المرور غير صحيحة",
    INVALID_USER_ID: "هوية مستخدم غير صالحه",
    INVALID_USER_ID_OR_OTP: "معرف المستخدم أو OTP غير صالح",
    INVALID_RFP_ID: "معرف RFP غير صالح",
    RFP_CANCELLED: "تم إلغاء RFP بنجاح",
    STORES_FOUND: "تم العثور على {total} متجر (متاجر) بنجاح",
    STORES_NOT_FOUND: "المتاجر غير موجودة",
    UNABLE_TO_CANCEL_RFP: "تعذر إلغاء RFP",
    LOGGED_IN: "تم تسجيل الدخول بنجاح",
    UNABLE_TO_LOGIN: "غير قادر على تسجيل الدخول",
    LOGGED_OUT: "تم تسجيل الخروج بنجاح",
    UNABLE_TO_LOGOUT: "تعذر تسجيل الخروج",
    UNABLE_TO_LOGIN_INVALID_TOKEN: "غير قادر على تسجيل الدخول ، رمز غير صالح",
    OTP_SENT: "تم إرسال OTP بنجاح",
    YOU_CAN_RESET_PASSWORD_NOW: "يمكنك إعادة تعيين كلمة المرور الآن",
    YOU_ENTERED_OLD_PASSWORD:
      "لقد أدخلت كلمة مرور قديمة ، يرجى إدخال كلمة مرور جديدة",
    PASSWORD_RESET: "إعادة تعيين كلمة المرور بنجاح",
    UNABLE_TO_RESET_PASSWORD: "غير قادر على إعادة تعيين كلمة المرور",
    EMAIL_OR_PASSWORD_INCORRECT: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    TOKEN_RESUMED: "تم استئناف الرمز بنجاح",
    UNABLE_TO_RESUME_TOKEN: "تعذر استئناف الرمز المميز",
    LANGUAGE_CHANGED: "تغيرت اللغة بنجاح",
    UNABLE_TO_CHANGE_LANGUAGE:
      "غير قادر على تغيير اللغة. الرجاء معاودة المحاولة في وقت لاحق",
    PROPOSAL_CREATED: "تم إنشاء الاقتراح بنجاح",
    PROPOSAL_UPDATED: "تم تحديث الاقتراح بنجاح",
    UNABLE_TO_CREATE_PROPOSAL: "تعذر إنشاء الاقتراح",
    UNABLE_TO_UPDATE_PROPOSAL: "تعذر تحديث الاقتراح",
    PROPOSAL_ALREADY_EXITS: "الدعامة موجودة بالفعل",
    REVIEWS_FOUND: "تم العثور على {total} من المراجعات بنجاح",
    REVIEWS_NOT_FOUND: "التعليقات والتقييمات غير موجودة",
    PRODUCTS_FOUND: "تم العثور على {total} منتج (منتجات) بنجاح",
    PRODUCTS_NOT_FOUND: "المنتجات غير موجودة",
    CATEGORIES_FOUND: "تم العثور على {total} فئة (فئات) بنجاح",
    CATEGORIES_NOT_FOUND: "فئة (ق) غير موجودة",
    PROFILE_UPDATED: "تم تحديث الملف الشخصي بنجاح",
    UPDATED: "تم التحديث بنجاح",
    UNABLE_TO_UPDATE: "غير قادر على التحديث",
    NOTHING_TO_UPDATE: "لا شيء لتحديث",
    CREATED: "تم إنشاؤه بنجاح",
    UNABLE_TO_CREATE: "غير قادر على إنشاء",
    INVALID_ID: "هوية غير صحيحة",
    PROPOSALS_FOUND: "تم العثور على {total} من العروض بنجاح",
    PROPOSAL_FOUND: "تم العثور على الاقتراح بنجاح",
    PROPOSALS_NOT_FOUND: "الاقتراحات غير موجودة",
    PROPOSAL_NOT_FOUND: "العرض غير موجود",
    ANOTHER_ORDER_ASSIGNED_TO_DRIVER_ALREADY:
      "تم تعيين طلب آخر لبرنامج التشغيل هذا بالفعل",
    ASSIGNED_TO_DRIVER: "تم تعيينه للسائق بنجاح",
    INVALID_ORDER_ID: "هوية الطلب غير صالحة",
    UNABLE_TO_ASSIGN_DRIVER: "تعذر تعيين سائق",
    LOCATIONS_FOUND: "تم العثور على {total} من المواقع بنجاح",
    LOCATIONS_NOT_FOUND: "المواقع غير موجودة",
    UNABLE_TO_FIND_LOCATIONS: "تعذر العثور على المواقع",
    BUSINESS_ALREADY_REGISTERED: "النشاط التجاري مسجل بالفعل",
    BUSINESS_EXISTS_WITH_PHONE_NO: "العمل مع رقم الهاتف موجود بالفعل",
    BUSINESS_REGISTRATION_REQUIRED: "مطلوب تسجيل الأعمال",
    BUSINESS_REGISTERED: "تم تسجيل العمل بنجاح ، يتطلب موافقة المسؤول",
    TOTAL_USERS_FOUND: "تم العثور على {total} مستخدم بنجاح",
    INVALID_PROPOSAL_ID: "هوية الاقتراح غير صالحة",
    PROPOSAL_RESPONDED: "الاقتراح {status} بنجاح",
    ROLE_ALREADY_EXISTS: "الدور بهذا الاسم موجود بالفعل",
    TOTAL_ROLES_FOUND: "تم العثور على {total} دور (أدوار) بنجاح",
    TOTAL_RECORDS_FOUND: "وجدت بنجاح {records} {total}",
    ROLE_FOUND: "تم العثور على الدور بنجاح",
    ROLES_NOT_FOUND: "الأدوار غير موجودة",
    INVALID_ROLE_ID: "هوية دور غير صالحة",
    EMAIL_PASSWORD_REQUIRED_FOR_ONLINE_DRIVER:
      "مطلوب البريد الإلكتروني وكلمة المرور للسائق عبر الإنترنت",
    DRIVER_ADDED: "تمت إضافة السائق بنجاح",
    UNABLE_TO_ADD_DRIVER: "غير قادر على إضافة سائق",
    DELETED: "حذف بنجاح",
    UNABLE_TO_DELETE: "تعذر الحذف",
    ROLE_CANT_BE_DELETED: "لا يمكن حذف هذا الدور",
    PERMISSION_ALREADY_EXISTS: "الإذن بهذا الاسم موجود بالفعل",
    PERMISSIONS_FOUND: "تم العثور على الأذونات بنجاح",
    PERMISSIONS_NOT_FOUND: "الأذونات غير موجودة",
    ORDER_FOUND: "تم العثور على الطلب بنجاح",
    ORDER_NOT_FOUND: "الطلب غير موجود",
    UNABLE_TO_PROCESS: "غير قادر على المعالجة",
    PROPOSAL_REVISED: "تمت مراجعة الاقتراح بنجاح",
    SOME_INVALID_ITEMS: "تحتوي الحمولة على بعض العناصر غير الصالحة",
    PERMISSIONS_ASSIGNED: "تم تعيين الأذونات بنجاح",
    UNABLE_TO_ASSIGN_PERMISSIONS: "تعذر تعيين الأذونات",
    INVALID_DRIVER_ID: "هوية السائق غير صالحة",
    DRIVER_IS_OFFLINE: "السائق غير متصل",
    DRIVER_UPDATED: "تم تحديث برنامج التشغيل بنجاح",
    DRIVER_DELETED: "تم حذف برنامج التشغيل بنجاح",
    FORM_SUBMITTED: "في محطة للحافلات",
    UNABLE_TO_SUBMIT_FORM: "غير قادر على إرسال النموذج",
    STATUS_CHANGED: "تم تغيير الوضع بنجاح",
    UNABLE_TO_CHANGE_STATUS: "غير قادر على تغيير الحالة",
    ORDER_REQUEST_FOUND: "تم العثور على طلب الطلب بنجاح",
    UNABLE_TO_GET_ORDER_REQUEST: "تعذر الحصول على طلب الطلب",
    FOUND: "وجدت بنجاح",
    NOT_FOUND: "غير موجود",
    DRIVERS_FOUND: "تم العثور على {total} سائق (سائقين) بنجاح",
    DRIVERS_NOT_FOUND: "السائقين غير موجود",
    INVALID_ORDER_REQUEST_ID: "هوية طلب طلب غير صالحة",
    UNABLE_TO_PROCESS: "غير قادر على المعالجة",
    ACCEPTED_SUCCESSFULLY: "تم القبول بنجاح",
    REJECTED_SUCCESSFULLY: "تم الرفض بنجاح",
    DRIVER_HAS_DIFFERENT_VEHICLE: "السائق لديه مركبة مختلفة",
    YOU_DONT_HAVE_ENOUGH_CREDIT: "ليس لديك رصيد كاف للدفع",
    PAID: "تم الدفع بنجاح",
    ADDED_TO_WALLET: "تمت الإضافة إلى المحفظة بنجاح",
    DELIVERY_MODE_AND_DELIVERY_VEHICLE_REQUIRED:
      "مطلوب وضع التسليم ومركبة التسليم",
    RFP_HAS_BEEN_EXPIRED: "انتهت صلاحية طلب تقديم العروض",
    RFP_HAS_BEEN_CANCELLED: "تم إلغاء طلب تقديم العروض",
    FORGET_PASSWORD_EMAIL_MSG:
      "<p>Waspha Forget Password OTP is <b>: {OTP} </b></p>",
    FORGET_PASSWORD_PHONE_MSG: "Waspha Forget Password OTP is: {OTP}",
    RESEND_OTP_EMAIL_MSG: "<p>Waspha Verification OTP is <b>: {OTP} </b></p>",
    RESEND_OTP_PHONE_MSG: "OTP للتحقق من وصفة هو: {OTP}",
    CATEGORY_WITH_SLUG_ALREADY_EXIST:
      "الفئة التي تحتوي على هذا الارتفاع الثابت موجودة بالفعل",
    CATEGORY_WITH_NAME_ALREADY_EXIST: "الفئة بهذا الاسم موجودة بالفعل",
    INVALID_PARENT_ID: "هوية الوالد غير صالحة",
    UNABLE_TO_REGISTER: "غير قادر على التسجيل",
    INCORRECT_OLD_PASSWORD: "كلمة السر القديمة غير صحيحة",
    CHANGED: "تم التغيير بنجاح",
    UNABLE_TO_CHANGE: "غير قادر على التغيير",
    SUBMITTED: "تم الإرسال بنجاح",
    UNABLE_TO_SUBMIT: "غير قادر على الإرسال",
    UNABLE_TO_FIND: "تعذر العثور",
    INVALID_PROMO_CODE: "الرمز الترويجي غير صالح",
    APPLIED: "الرمز الترويجي غير صالح",
    YOU_ARE_NOT_ALLOWED_TO_USE_THIS_PROMO: "الرمز الترويجي غير صالح",
    PROMO_IS_NOT_APPLICABLE_TO_SELECTED_PAYMENT_METHOD:
      "الرمز الترويجي غير صالح",
    PROMO_IS_NOT_APPLICABLE_TO_SELECTED_SERVICE_MODE: "الرمز الترويجي غير صالح",
    PROMO_IS_NOT_APPLICABLE_TO_SELECTED_CATEGORY: "الرمز الترويجي غير صالح",
    PROMO_LIMIT_REACHED: "الرمز الترويجي غير صالح",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_SUBTOTAL: "الرمز الترويجي غير صالح",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_TOTAL: "الرمز الترويجي غير صالح",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_DELIVERY_FEE: "الرمز الترويجي غير صالح",
    PROMO_MIN_ORDER_AMOUNT_NOT_REACHED_WASPHA_FEE: "الرمز الترويجي غير صالح",
    YOU_CANT_REVISE_WITH_ZERO_QUANTITY: "لا يمكنك المراجعة بكمية صفرية",
    PASSWORD_CHANGED: "تم تغيير كلمة المرور بنجاح",
    INVALID_STORE_ID: "هوية المتجر غير صالحة",
    YOU_HAVE_AN_ACTIVE_ORDER_ALREADY: "لديك طلب نشط بالفعل",
    INVALID_SUBCATEGORY: "فئة فرعية غير صالحة",
    RFP_CREATED: "تم إنشاء RFP بنجاح",
    CODE_SENT_IF_YOU_ARE_REGISTERED_USER:
      "تم إرسال الرمز إذا كنت مستخدمًا مسجلاً",
    UNABLE_TO_CHANGE_DELIVERY_MODE_AVAILABILITY: "تعذر تغيير توفر وضع التسليم",
    ADDED: "اضيف بنجاح",
    ADMIN_APPROVAL_REQUIRED: "موافقة المسؤول مطلوبة",
    PLEASE_SPECIFY_FIXED_ZONE_OR_FREE_ZONE:
      "الرجاء تحديد منطقة ثابتة أو منطقة حرة",
    INVALID_FIXED_ZONE_ID: "هوية المنطقة الثابتة غير صالحة",
    NO_NEED_TO_CHANGE: "لا حاجة للتغيير",
    INVALID_REFERRAL_CODE: "رمز الإحالة غير صالح",
    VERIFY_EMAIL_MSG: "<p>Waspha Verify Email OTP is <b>: {OTP} </b></p>",
    VERIFY_CONTACT_MSG: "<p>Waspha Verify Phone OTP is <b>: {OTP} </b></p>",
    EMAIL_VERIFIED: "Email verified successfully",
    CONTACT_VERIFIED: "Contact verified successfully",
    EMAIL_IS_SAME: "Email is same,no need to change",
    CONTACT_IS_SAME: "Contact is same,no need to change",
    FORGET_PASSWORD: "نسيت كلمة المرور",
    RESEND_OTP: "Resend OTP",
    FROM: "من",
    TO: "إلى",
    FULLTIME: "وقت كامل",
    DAY: {
      Sunday: "الأحد",
      Monday: "الإثنين",
      Tuesday: "الثلاثاء",
      Wednesday: "الأربعاء",
      Thursday: "الخميس",
      Friday: "الجمعة",
      Saturday: "السبت",
    },
    MONTH: {
      January: "الأحد",
      February: "الإثنين",
      March: "الثلاثاء",
      April: "الأربعاء",
      May: "الخميس",
      June: "الجمعة",
      July: "السبت",
      August: "السبت",
      September: "السبت",
      October: "السبت",
      November: "السبت",
      December: "السبت",
    },
  },
};

module.exports.notification = {
  type: {
    ///general
    ORDER_COMPLETED: "order_completed",
    REVIEW_RECEIVED: "review_received",
    RFP_CANCELLED: "rfp_cancelled",
    LOYALTY_POINTS_UPDATED: "loyalty_points_updated",

    ///user
    PROPOSAL_RECEIVED: "proposal_received",
    RFP_REJECTED: "rfp_rejected",
    REVISION_RECEIVED: "revision_received",
    RFP_EXPIRED: "rfp_expired",
    QUEUE_CALLED: "queue_called",
    RIDER_ASSIGNED: "rider_assigned",
    RIDER_CHANGED: "rider_changed",
    ADMIN_MESSAGE: "admin_message",
    DELIVERY_MODE_CHANGED: "delivery_mode_changed",
    NO_VENDORS_FOUND: "no_vendors_found",
    REVISION_ACCEPTED: "revision_accepted",
    REVISION_REJECTED: "revision_rejected",
    WALLET_ADDED: "wallet_added",

    ///vendor
    RFP_RECEIVED: "rfp_received",
    RFP_TIMEOUT: "rfp_timeout",
    PROPOSAL_ACCEPTED: "proposal_accepted",
    PROPOSAL_REJECTED: "proposal_rejected",
    PROPOSAL_REVISED: "proposal_revised",
    ORDER_DELIVERED_BY_DRIVER: "order_delivered_by_driver",
    PAYMENT_RECEIVED_VIA_ONLINE_METHOD: "payment_received_via_online_method",
    SCHEDULED_DELIVERY_TIMING_IS_COMING: "scheduled_delivery_timing_is_coming",
    PROPOSAL_EXPIRED: "proposal_expired",
    MESSAGE_FROM_ADMIN: "message_from_admin",
    ACCOUNT_APPROVED: "account_approved",
    ACCOUNT_DISAPPROVED: "account_disapproved",
    ONLINE_STATUS_UPDATED: "online_status_updated",
    DRIVER_FOUND: "driver_found",
    NO_DRIVER_FOUND: "no_driver_found",
    EXPRESS_DRIVER_FOUND: "express_driver_found",
    NO_EXPRESS_DRIVER_FOUND: "no_express_driver_found",
    DRIVER_ORDER_REJECTED: "driver_order_rejected",
    EXPRESS_DRIVER_ORDER_REJECTED: "express_driver_order_rejected",
    //driver
    ORDER_REQUEST_RECEIVED: "order_request_received",
  },
};

// date time formats
// export const DATE_TIME_FORMAT = 'DD/MM/YY, hh:mm a';
// export const DATE_FORMAT1 = 'dddd, DD MMMM, YYYY';
// export const DATE_FORMAT2 = 'DD/MM/YYYY';
// export const DATE_FORMAT3 = 'DD MMMM, YYYY';
// export const DATE_FORMAT4 = 'ddd';
// export const DATE_FORMAT5 = 'DD-MM-YYYY';
// export const TIME_FORMAT2 = 'hh:mm';
// export const TIME_FORMAT3 = 'h:mm a';
// export const TIME_FORMAT = 'hh:mm a';
// export const DATE_TIME = 'DD-MM-YYYY hh:mm a';
